package dovecot

import (
	"fmt"
	"os"
	"path/filepath"
)

type ConfigOptions struct {
	ConfigDir        string
	TargetConfigPath string
	VmailRoot        string
	VmailUID         int
	VmailGID         int
	DBHost           string
	DBPort           int
	DBName           string
	DBUser           string
	DBPassword       string
}

type GeneratedConfigs struct {
	DovecotConf string
	MailConf    string
	SSLConf     string
	AuthConf    string
	MasterConf  string
	AuthSQLConf string
	PgSQLConf   string
}


func GenerateConfigs(opts ConfigOptions) GeneratedConfigs {
	configPathPrefix := opts.TargetConfigPath
	if configPathPrefix == "" {
		absConfigDir, _ := filepath.Abs(opts.ConfigDir)
		configPathPrefix = absConfigDir
	}

	sqlConfPath := filepath.Join(configPathPrefix, "sql", "dovecot-pgsql.conf.ext")

	dovecotConf := `# Dovecot configuration generated by MailOpen (Control Plane)
protocols = imap
listen = *
base_dir = /var/run/dovecot/
login_greeting = Dovecot ready.
ssl = no
log_path = /dev/stderr
info_log_path = /dev/stdout

!include conf.d/*.conf
!include_try local.conf
`

	mailConf := fmt.Sprintf(`# 10-mail.conf generated by MailOpen
mail_location = maildir:%s/%%d/%%n/Maildir
mail_uid = %d
mail_gid = %d
mail_privileged_group = vmail
first_valid_uid = %d
last_valid_uid = %d

namespace inbox {
  inbox = yes
}
`,
		opts.VmailRoot,
		opts.VmailUID,
		opts.VmailGID,
		opts.VmailUID,
		opts.VmailUID,
	)


	sslConf := `# 10-ssl.conf generated by MailOpen
ssl = no
`

	authConf := `# 10-auth.conf generated by MailOpen
disable_plaintext_auth = no
auth_mechanisms = plain login
auth_username_format = %Lu

!include auth-sql.conf.ext
`

	masterConf := `# 10-master.conf generated by MailOpen
service imap-login {
  inet_listener imap {
    port = 143
  }
}

service auth {
  unix_listener auth-userdb {
    mode = 0660
    user = vmail
    group = vmail
  }
  unix_listener auth-client {
    mode = 0660
  }
  # Postfix SMTP AUTH Dovecot SASL listener
  unix_listener /var/spool/postfix/private/auth {
    mode = 0666
  }
}
`



	authSQLConf := fmt.Sprintf(`# auth-sql.conf.ext generated by MailOpen
passdb {
  driver = sql
  args = %s
}

userdb {
  driver = sql
  args = %s
}
`,
		sqlConfPath,
		sqlConfPath,
	)

	pgsqlConf := fmt.Sprintf(`# dovecot-pgsql.conf.ext generated by MailOpen
driver = pgsql
connect = host=%s port=%d dbname=%s user=%s password=%s
default_pass_scheme = ARGON2ID

password_query = SELECT email AS username, password_hash AS password FROM mailboxes WHERE LOWER(email) = LOWER('%%u') AND status = 'active' AND provisioning_status = 'ready' LIMIT 1;

user_query = SELECT %d AS uid, %d AS gid, '%s/%%d/%%n/Maildir' AS home FROM mailboxes WHERE LOWER(email) = LOWER('%%u') AND status = 'active' AND provisioning_status = 'ready' LIMIT 1;

iterate_query = SELECT email AS username FROM mailboxes WHERE status = 'active' AND provisioning_status = 'ready';
`,
		opts.DBHost,
		opts.DBPort,
		opts.DBName,
		opts.DBUser,
		opts.DBPassword,
		opts.VmailUID,
		opts.VmailGID,
		opts.VmailRoot,
	)

	return GeneratedConfigs{
		DovecotConf: dovecotConf,
		MailConf:    mailConf,
		SSLConf:     sslConf,
		AuthConf:    authConf,
		MasterConf:  masterConf,
		AuthSQLConf: authSQLConf,
		PgSQLConf:   pgsqlConf,
	}
}

// WriteConfigsAtomically writes all generated Dovecot configuration files atomically using temporary files and safe permissions.
func WriteConfigsAtomically(opts ConfigOptions) error {
	absConfigDir, err := filepath.Abs(opts.ConfigDir)
	if err != nil {
		return fmt.Errorf("invalid config dir: %w", err)
	}

	confDDir := filepath.Join(absConfigDir, "conf.d")
	sqlDir := filepath.Join(absConfigDir, "sql")

	if err := os.MkdirAll(confDDir, 0750); err != nil {
		return fmt.Errorf("failed to create conf.d directory: %w", err)
	}
	if err := os.MkdirAll(sqlDir, 0750); err != nil {
		return fmt.Errorf("failed to create sql directory: %w", err)
	}

	configs := GenerateConfigs(opts)

	fileMap := []struct {
		path string
		data string
		perm os.FileMode
	}{
		{filepath.Join(absConfigDir, "dovecot.conf"), configs.DovecotConf, 0644},
		{filepath.Join(confDDir, "10-mail.conf"), configs.MailConf, 0644},
		{filepath.Join(confDDir, "10-ssl.conf"), configs.SSLConf, 0644},
		{filepath.Join(confDDir, "10-auth.conf"), configs.AuthConf, 0644},
		{filepath.Join(confDDir, "10-master.conf"), configs.MasterConf, 0644},
		{filepath.Join(confDDir, "auth-sql.conf.ext"), configs.AuthSQLConf, 0644},
		{filepath.Join(sqlDir, "dovecot-pgsql.conf.ext"), configs.PgSQLConf, 0640},
	}


	for _, item := range fileMap {
		dir := filepath.Dir(item.path)
		if err := atomicWriteFile(dir, item.path, []byte(item.data), item.perm); err != nil {
			return fmt.Errorf("failed writing %s: %w", item.path, err)
		}
	}

	return nil
}

func atomicWriteFile(dir, targetPath string, content []byte, perm os.FileMode) error {
	tempFile, err := os.CreateTemp(dir, "dovecot-conf-*")
	if err != nil {
		return err
	}
	tempPath := tempFile.Name()
	defer func() {
		if _, err := os.Stat(tempPath); err == nil {
			_ = os.Remove(tempPath)
		}
	}()

	if _, err := tempFile.Write(content); err != nil {
		_ = tempFile.Close()
		return err
	}

	if err := tempFile.Sync(); err != nil {
		_ = tempFile.Close()
		return err
	}

	if err := tempFile.Close(); err != nil {
		return err
	}

	if err := os.Chmod(tempPath, perm); err != nil {
		return err
	}

	return os.Rename(tempPath, targetPath)
}
