package dkim

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type OpenDKIMConfigOptions struct {
	ConfigDir        string // e.g. ./data/opendkim (where files are written)
	TargetConfigPath string // e.g. /etc/mailopen/opendkim (path inside container)
	DKIMBaseDir      string // e.g. /etc/mailopen/dkim
	SocketPath       string // e.g. /var/spool/postfix/private/opendkim
	ActiveKeys       []*DKIMKey
	TrustedHosts     []string
}

type OpenDKIMGeneratedConfigs struct {
	OpenDKIMConf string
	KeyTable     string
	SigningTable string
	TrustedHosts string
}

func GenerateOpenDKIMConfigs(opts OpenDKIMConfigOptions) OpenDKIMGeneratedConfigs {
	socket := opts.SocketPath
	if socket == "" {
		socket = "local:/var/spool/postfix/private/opendkim"
	}
	if !strings.HasPrefix(socket, "local:") && !strings.HasPrefix(socket, "inet:") {
		socket = "local:" + socket
	}

	dkimBase := opts.DKIMBaseDir
	if dkimBase == "" {
		dkimBase = "/etc/mailopen/dkim"
	}

	confDir := opts.TargetConfigPath
	if confDir == "" {
		confDir = "/etc/mailopen/opendkim"
	}


	opendkimConf := fmt.Sprintf(`# OpenDKIM configuration generated by MailOpen (Control Plane)
AutoRestart             Yes
AutoRestartRate         10/1h
UMask                   002
Syslog                  Yes
SyslogSuccess           Yes
LogWhy                  Yes

Canonicalization        relaxed/simple
Mode                    s
SubDomains              no

Socket                  %s
PidFile                 /var/run/opendkim/opendkim.pid
UserID                  postfix:postfix

KeyTable                refile:%s/KeyTable
SigningTable            refile:%s/SigningTable
ExternalIgnoreList      refile:%s/TrustedHosts
InternalHosts           refile:%s/TrustedHosts
`,
		socket,
		confDir,
		confDir,
		confDir,
		confDir,
	)

	var keyTableLines []string
	var signingTableLines []string

	for _, k := range opts.ActiveKeys {
		if k.Status != StatusActive && k.Status != StatusPending {
			continue
		}
		domain := strings.ToLower(k.Domain)
		selector := strings.ToLower(k.Selector)
		keyName := fmt.Sprintf("%s._domainkey.%s", selector, domain)
		keyPath := fmt.Sprintf("%s/%s/%s/private.key", dkimBase, domain, selector)

		keyTableLines = append(keyTableLines, fmt.Sprintf("%s %s:%s:%s", keyName, domain, selector, keyPath))
		signingTableLines = append(signingTableLines, fmt.Sprintf("*@%s %s", domain, keyName))
		signingTableLines = append(signingTableLines, fmt.Sprintf("%s %s", domain, keyName))
	}

	keyTable := fmt.Sprintf("# OpenDKIM KeyTable generated by MailOpen\n%s\n", strings.Join(keyTableLines, "\n"))
	signingTable := fmt.Sprintf("# OpenDKIM SigningTable generated by MailOpen\n%s\n", strings.Join(signingTableLines, "\n"))

	hosts := opts.TrustedHosts
	if len(hosts) == 0 {
		hosts = []string{"127.0.0.1", "::1", "localhost"}
	}
	trustedHosts := fmt.Sprintf("# OpenDKIM TrustedHosts generated by MailOpen\n%s\n", strings.Join(hosts, "\n"))

	return OpenDKIMGeneratedConfigs{
		OpenDKIMConf: opendkimConf,
		KeyTable:     keyTable,
		SigningTable: signingTable,
		TrustedHosts: trustedHosts,
	}
}

func WriteOpenDKIMConfigsAtomically(opts OpenDKIMConfigOptions) error {
	outDir := opts.ConfigDir
	if outDir == "" {
		outDir = "./data/opendkim"
	}

	if err := os.MkdirAll(outDir, 0750); err != nil {
		return fmt.Errorf("create opendkim config dir %s: %w", outDir, err)
	}

	configs := GenerateOpenDKIMConfigs(opts)

	files := map[string]string{
		"opendkim.conf": configs.OpenDKIMConf,
		"KeyTable":      configs.KeyTable,
		"SigningTable":  configs.SigningTable,
		"TrustedHosts":  configs.TrustedHosts,
	}

	for filename, content := range files {
		targetPath := filepath.Join(outDir, filename)
		tmpFile, err := os.CreateTemp(outDir, filename+".tmp-*")
		if err != nil {
			return fmt.Errorf("create temp file for %s: %w", filename, err)
		}
		tmpName := tmpFile.Name()

		if _, err := tmpFile.WriteString(content); err != nil {
			_ = tmpFile.Close()
			_ = os.Remove(tmpName)
			return fmt.Errorf("write %s: %w", filename, err)
		}

		if err := tmpFile.Sync(); err != nil {
			_ = tmpFile.Close()
			_ = os.Remove(tmpName)
			return fmt.Errorf("sync %s: %w", filename, err)
		}

		if err := tmpFile.Chmod(0644); err != nil {
			_ = tmpFile.Close()
			_ = os.Remove(tmpName)
			return fmt.Errorf("chmod %s: %w", filename, err)
		}

		if err := tmpFile.Close(); err != nil {
			_ = os.Remove(tmpName)
			return fmt.Errorf("close %s: %w", filename, err)
		}

		if err := os.Rename(tmpName, targetPath); err != nil {
			_ = os.Remove(tmpName)
			return fmt.Errorf("rename %s: %w", filename, err)
		}
	}

	return nil
}
