ALTER TABLE domain_mail_policy
    ADD COLUMN IF NOT EXISTS spam_threshold DOUBLE PRECISION NOT NULL DEFAULT 6.0,
    ADD COLUMN IF NOT EXISTS reject_threshold DOUBLE PRECISION NOT NULL DEFAULT 15.0,
    ADD COLUMN IF NOT EXISTS quarantine_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS max_message_size BIGINT NOT NULL DEFAULT 26214400,
    ADD COLUMN IF NOT EXISTS rbl_policy TEXT NOT NULL DEFAULT 'log-only',
    ADD COLUMN IF NOT EXISTS rdns_policy TEXT NOT NULL DEFAULT 'relaxed';
