services:
  postgres:
    image: postgres:16-alpine
    container_name: mailopen_postgres
    environment:
      POSTGRES_USER: mailopen
      POSTGRES_PASSWORD: mailopen
      POSTGRES_DB: mailopen
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mailopen -d mailopen"]
      interval: 3s
      timeout: 3s
      retries: 5

  postfix:
    build:
      context: ..
      dockerfile: deploy/postfix/Dockerfile
    image: openmail-postfix:latest
    container_name: mailopen_postfix
    ports:
      - "25:25"
    volumes:
      - ../data/vmail:/var/vmail
      - ../data/postfix:/config
    depends_on:
      postgres:
        condition: service_healthy

  dovecot:
    build:
      context: ..
      dockerfile: deploy/dovecot/Dockerfile
    image: openmail-dovecot:latest
    container_name: mailopen_dovecot
    ports:
      - "143:143"
    volumes:
      - ../data/vmail:/var/vmail
      - ../data/dovecot:/config
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
