package postfix

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type ConfigOptions struct {
	ConfigDir  string
	Hostname   string
	VmailRoot  string
	VmailUID   int
	VmailGID   int
	DBHost     string
	DBPort     int
	DBName     string
	DBUser     string
	DBPassword string
}

type GeneratedConfigs struct {
	MainCF                  string
	MasterCF                string
	VirtualMailboxDomainsCF string
	VirtualMailboxMapsCF    string
	VirtualAliasMapsCF      string
}

func GenerateConfigs(opts ConfigOptions) GeneratedConfigs {
	absConfigDir, _ := filepath.Abs(opts.ConfigDir)

	domainsCFPath := filepath.Join(absConfigDir, "pgsql-virtual-mailbox-domains.cf")
	mailboxCFPath := filepath.Join(absConfigDir, "pgsql-virtual-mailbox-maps.cf")
	aliasCFPath := filepath.Join(absConfigDir, "pgsql-virtual-alias-maps.cf")

	mainCF := fmt.Sprintf(`# Postfix configuration generated by MailOpen (Control Plane)
myhostname = %s
inet_interfaces = all
inet_protocols = all

mydestination = localhost
relay_domains =

# Virtual Domain & Mailbox Maps via PostgreSQL
virtual_mailbox_domains = pgsql:%s
virtual_mailbox_maps = pgsql:%s
virtual_alias_maps = pgsql:%s

# Virtual Mailbox Delivery Configuration (Dovecot Maildir++)
virtual_transport = virtual
virtual_minimum_uid = %d
virtual_uid_maps = static:%d
virtual_gid_maps = static:%d
virtual_mailbox_base = %s

# Security baseline & Anti-Relay protection (Inbound SMTP :25)
smtpd_helo_required = yes
smtpd_delay_reject = yes
smtpd_relay_restrictions = permit_mynetworks, reject_unauth_destination
smtpd_recipient_restrictions = permit_mynetworks, reject_unauth_destination
`,
		opts.Hostname,
		domainsCFPath,
		mailboxCFPath,
		aliasCFPath,
		opts.VmailUID,
		opts.VmailUID,
		opts.VmailGID,
		opts.VmailRoot,
	)

	masterCF := `# Postfix master process configuration generated by MailOpen
# ==========================================================================
# service type  private unpriv  chroot  wakeup  maxproc command + args
#               (yes)   (yes)   (no)    (never) (100)
# ==========================================================================
smtp      inet  n       -       n       -       -       smtpd
cleanup   unix  n       -       n       -       0       cleanup
qmgr      unix  n       -       n       300     1       qmgr
rewrite   unix  -       -       n       -       -       trivial-rewrite
bounce    unix  -       -       n       -       0       bounce
defer     unix  -       -       n       -       0       bounce
trace     unix  -       -       n       -       0       bounce
verify    unix  -       -       n       -       1       verify
flush     unix  n       -       n       1000?   0       flush
proxymap  unix  -       -       n       -       -       proxymap
proxywrite unix -       -       n       -       1       proxymap
virtual   unix  -       n       n       -       -       virtual
anvil     unix  -       -       n       -       1       anvil
scache    unix  -       -       n       -       1       scache
`

	domainsCF := fmt.Sprintf(`# PostgreSQL Virtual Mailbox Domains Map
hosts = %s:%d
user = %s
password = %s
dbname = %s
query = SELECT 1 FROM domains WHERE LOWER(name) = LOWER('%%s') AND status = 'active' LIMIT 1
`,
		opts.DBHost, opts.DBPort, opts.DBUser, opts.DBPassword, opts.DBName,
	)

	mailboxCF := fmt.Sprintf(`# PostgreSQL Virtual Mailbox Map (only active & ready mailboxes)
hosts = %s:%d
user = %s
password = %s
dbname = %s
query = SELECT 1 FROM mailboxes m JOIN domains d ON d.id = m.domain_id WHERE LOWER(m.email) = LOWER('%%s') AND m.status = 'active' AND m.provisioning_status = 'ready' LIMIT 1
`,
		opts.DBHost, opts.DBPort, opts.DBUser, opts.DBPassword, opts.DBName,
	)

	aliasCF := fmt.Sprintf(`# PostgreSQL Virtual Alias Map
hosts = %s:%d
user = %s
password = %s
dbname = %s
query = SELECT a.destination FROM aliases a JOIN domains d ON d.id = a.domain_id WHERE LOWER(a.source) = LOWER('%%s') AND d.status = 'active'
`,
		opts.DBHost, opts.DBPort, opts.DBUser, opts.DBPassword, opts.DBName,
	)

	return GeneratedConfigs{
		MainCF:                  mainCF,
		MasterCF:                masterCF,
		VirtualMailboxDomainsCF: domainsCF,
		VirtualMailboxMapsCF:    mailboxCF,
		VirtualAliasMapsCF:      aliasCF,
	}
}

// WriteConfigsAtomically writes all generated configuration files atomically using temporary files and safe permissions.
func WriteConfigsAtomically(opts ConfigOptions) error {
	absConfigDir, err := filepath.Abs(opts.ConfigDir)
	if err != nil {
		return fmt.Errorf("invalid config dir: %w", err)
	}

	if err := os.MkdirAll(absConfigDir, 0750); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	configs := GenerateConfigs(opts)

	fileMap := map[string]string{
		"main.cf":                            configs.MainCF,
		"master.cf":                          configs.MasterCF,
		"pgsql-virtual-mailbox-domains.cf":  configs.VirtualMailboxDomainsCF,
		"pgsql-virtual-mailbox-maps.cf":     configs.VirtualMailboxMapsCF,
		"pgsql-virtual-alias-maps.cf":       configs.VirtualAliasMapsCF,
	}

	for filename, content := range fileMap {
		targetPath := filepath.Join(absConfigDir, filename)
		if err := atomicWriteFile(absConfigDir, targetPath, []byte(content), 0640); err != nil {
			return fmt.Errorf("failed writing %s: %w", filename, err)
		}
	}

	return nil
}

func atomicWriteFile(dir, targetPath string, content []byte, perm os.FileMode) error {
	tempFile, err := os.CreateTemp(dir, "postfix-conf-*")
	if err != nil {
		return err
	}
	tempPath := tempFile.Name()
	defer func() {
		if _, err := os.Stat(tempPath); err == nil {
			_ = os.Remove(tempPath)
		}
	}()

	if _, err := tempFile.Write(content); err != nil {
		_ = tempFile.Close()
		return err
	}

	if err := tempFile.Sync(); err != nil {
		_ = tempFile.Close()
		return err
	}

	if err := tempFile.Close(); err != nil {
		return err
	}

	if err := os.Chmod(tempPath, perm); err != nil {
		return err
	}

	return os.Rename(tempPath, targetPath)
}

func MaskSecret(s string) string {
	if len(s) <= 4 {
		return "****"
	}
	return s[:2] + strings.Repeat("*", len(s)-4) + s[len(s)-2:]
}
