package postfix

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type ConfigOptions struct {
	ConfigDir        string
	TargetConfigPath string
	Hostname         string
	VmailRoot        string
	VmailUID         int
	VmailGID         int
	DBHost           string
	DBPort           int
	DBName           string
	DBUser           string
	DBPassword       string
	TLSCertFile      string
	TLSKeyFile       string
	MilterSocket     string
}

type GeneratedConfigs struct {
	MainCF                  string
	MasterCF                string
	VirtualMailboxDomainsCF string
	VirtualMailboxMapsCF    string
	VirtualAliasMapsCF      string
	SenderLoginMapsCF       string
}

func GenerateConfigs(opts ConfigOptions) GeneratedConfigs {
	configPathPrefix := opts.TargetConfigPath
	if configPathPrefix == "" {
		absConfigDir, _ := filepath.Abs(opts.ConfigDir)
		configPathPrefix = absConfigDir
	}

	domainsCFPath := filepath.Join(configPathPrefix, "pgsql-virtual-mailbox-domains.cf")
	mailboxCFPath := filepath.Join(configPathPrefix, "pgsql-virtual-mailbox-maps.cf")
	aliasCFPath := filepath.Join(configPathPrefix, "pgsql-virtual-alias-maps.cf")
	senderLoginCFPath := filepath.Join(configPathPrefix, "pgsql-sender-login-maps.cf")

	certFile := opts.TLSCertFile
	if certFile == "" {
		certFile = fmt.Sprintf("/etc/mailopen/tls/%s/fullchain.pem", opts.Hostname)
	}
	keyFile := opts.TLSKeyFile
	if keyFile == "" {
		keyFile = fmt.Sprintf("/etc/mailopen/tls/%s/privkey.pem", opts.Hostname)
	}

	milterSocket := opts.MilterSocket
	if milterSocket == "" {
		milterSocket = "unix:private/opendkim"
	}

	mainCF := fmt.Sprintf(`# Postfix configuration generated by MailOpen (Control Plane)
compatibility_level = 3.6
myhostname = %s
inet_interfaces = all
inet_protocols = all

# Log output directly to stdout for containers/diagnostics
maillog_file = /dev/stdout

mydestination = localhost
relay_domains =

# Virtual Domain & Mailbox Maps via PostgreSQL (proxymap)
virtual_mailbox_domains = proxy:pgsql:%s
virtual_mailbox_maps = proxy:pgsql:%s
virtual_alias_maps = proxy:pgsql:%s
smtpd_sender_login_maps = proxy:pgsql:%s

# Virtual Mailbox Delivery Configuration (Dovecot Maildir++)
virtual_transport = virtual
virtual_minimum_uid = %d
virtual_uid_maps = static:%d
virtual_gid_maps = static:%d
virtual_mailbox_base = %s

# Security baseline & Anti-Relay protection (Inbound SMTP :25)
smtpd_helo_required = yes
smtpd_delay_reject = yes
smtpd_relay_restrictions = permit_mynetworks, reject_unauth_destination

# Inbound SMTP :25 & :587 STARTTLS (Offered, minimum TLS 1.2, NO AUTH on port 25)
smtpd_tls_security_level = may
smtpd_tls_cert_file = %s
smtpd_tls_key_file = %s
smtpd_tls_protocols = >=TLSv1.2
smtpd_tls_mandatory_protocols = >=TLSv1.2
smtpd_tls_ciphers = medium
smtpd_tls_mandatory_ciphers = medium
tls_preempt_cipherlist = no

# Outbound SMTP Client TLS (Opportunistic TLS to external MTAs like Google Gmail, Outlook, Yahoo)
smtp_tls_security_level = may
smtp_tls_loglevel = 1
smtp_tls_protocols = >=TLSv1.2
smtp_tls_ciphers = medium
smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt

# OpenDKIM Milter (DKIM Outbound Signing)
smtpd_milters = %s
non_smtpd_milters = %s
milter_default_action = accept
milter_protocol = 6

# Baseline connection and message rate limits
smtpd_client_connection_count_limit = 200
smtpd_client_connection_rate_limit = 300
smtpd_client_message_rate_limit = 300
smtpd_client_event_limit_exceptions = $mynetworks, 127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16

# Anti-SMTP Smuggling Protection (CVE-2023-51764 & CVE-2023-51765)
smtpd_forbid_bare_newline = yes
smtpd_forbid_bare_newline_exclusions = $mynetworks
smtpd_data_restrictions = reject_unauth_pipelining

`,
		opts.Hostname,
		domainsCFPath,
		mailboxCFPath,
		aliasCFPath,
		senderLoginCFPath,
		opts.VmailUID,
		opts.VmailUID,
		opts.VmailGID,
		opts.VmailRoot,
		certFile,
		keyFile,
		milterSocket,
		milterSocket,
	)


	masterCF := fmt.Sprintf(`# Postfix master process configuration generated by MailOpen
# ==========================================================================
# service type  private unpriv  chroot  wakeup  maxproc command + args
#               (yes)   (yes)   (no)    (never) (100)
# ==========================================================================
# Port 25: Inbound MTA (Server-to-Server) - NO SMTP AUTH
smtp      inet  n       -       n       -       -       smtpd

# Port 587: Submission (Client-to-Server) - MANDATORY STARTTLS & SMTP AUTH
submission inet n       -       n       -       -       smtpd
  -o syslog_name=postfix/submission
  -o smtpd_tls_security_level=encrypt
  -o smtpd_tls_auth_only=yes
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_sasl_type=dovecot
  -o smtpd_sasl_path=/var/spool/postfix/private/auth
  -o smtpd_sasl_security_options=noanonymous
  -o smtpd_sasl_local_domain=$myhostname
  -o smtpd_sender_login_maps=proxy:pgsql:%s
  -o smtpd_sender_restrictions=reject_sender_login_mismatch,permit_sasl_authenticated,reject
  -o smtpd_recipient_restrictions=permit_sasl_authenticated,reject
  -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
  -o smtpd_client_connection_count_limit=200
  -o smtpd_client_connection_rate_limit=300



pickup    unix  n       -       n       60      1       pickup
cleanup   unix  n       -       n       -       0       cleanup
qmgr      unix  n       -       n       300     1       qmgr
tlsmgr    unix  -       -       n       1000?   1       tlsmgr
rewrite   unix  -       -       n       -       -       trivial-rewrite
bounce    unix  -       -       n       -       0       bounce
defer     unix  -       -       n       -       0       bounce
trace     unix  -       -       n       -       0       bounce
verify    unix  -       -       n       -       1       verify
flush     unix  n       -       n       1000?   0       flush
proxymap  unix  -       -       n       -       -       proxymap
proxywrite unix -       -       n       -       1       proxymap
smtp      unix  -       -       n       -       -       smtp
relay     unix  -       -       n       -       -       smtp
showq     unix  n       -       n       -       -       showq
error     unix  -       -       n       -       -       error
retry     unix  -       -       n       -       -       error
discard   unix  -       -       n       -       -       discard
local     unix  -       n       n       -       -       local
virtual   unix  -       n       n       -       -       virtual
lmtp      unix  -       -       n       -       -       lmtp
anvil     unix  -       -       n       -       1       anvil
scache    unix  -       -       n       -       1       scache
postlog   unix-dgram n  -       n       -       1       postlogd
`,
		senderLoginCFPath,
	)

	domainsCF := fmt.Sprintf(`# PostgreSQL Virtual Mailbox Domains Map
hosts = %s:%d
user = %s
password = %s
dbname = %s
query = SELECT 1 FROM domains WHERE LOWER(name) = LOWER('%%s') AND status = 'active' LIMIT 1
`,
		opts.DBHost, opts.DBPort, opts.DBUser, opts.DBPassword, opts.DBName,
	)

	mailboxCF := fmt.Sprintf(`# PostgreSQL Virtual Mailbox Map (returns relative Maildir path ending with /)
hosts = %s:%d
user = %s
password = %s
dbname = %s
query = SELECT d.name || '/' || split_part(m.email, '@', 1) || '/Maildir/' FROM mailboxes m JOIN domains d ON d.id = m.domain_id WHERE LOWER(m.email) = LOWER('%%s') AND m.status = 'active' AND m.provisioning_status = 'ready' LIMIT 1
`,
		opts.DBHost, opts.DBPort, opts.DBUser, opts.DBPassword, opts.DBName,
	)

	aliasCF := fmt.Sprintf(`# PostgreSQL Virtual Alias Map
hosts = %s:%d
user = %s
password = %s
dbname = %s
query = SELECT a.destination FROM aliases a JOIN domains d ON d.id = a.domain_id WHERE LOWER(a.source) = LOWER('%%s') AND d.status = 'active'
`,
		opts.DBHost, opts.DBPort, opts.DBUser, opts.DBPassword, opts.DBName,
	)

	senderLoginCF := fmt.Sprintf(`# PostgreSQL Sender Login Map (authorized senders & aliases)
hosts = %s:%d
user = %s
password = %s
dbname = %s
query = SELECT email FROM mailboxes WHERE LOWER(email) = LOWER('%%s') AND status = 'active' AND provisioning_status = 'ready' UNION SELECT a.destination AS email FROM aliases a JOIN domains d ON d.id = a.domain_id WHERE LOWER(a.source) = LOWER('%%s') AND d.status = 'active'
`,
		opts.DBHost, opts.DBPort, opts.DBUser, opts.DBPassword, opts.DBName,
	)

	return GeneratedConfigs{
		MainCF:                  mainCF,
		MasterCF:                masterCF,
		VirtualMailboxDomainsCF: domainsCF,
		VirtualMailboxMapsCF:    mailboxCF,
		VirtualAliasMapsCF:      aliasCF,
		SenderLoginMapsCF:       senderLoginCF,
	}
}

// WriteConfigsAtomically writes all generated configuration files atomically using temporary files and safe permissions.
func WriteConfigsAtomically(opts ConfigOptions) error {
	absConfigDir, err := filepath.Abs(opts.ConfigDir)
	if err != nil {
		return fmt.Errorf("invalid config dir: %w", err)
	}

	if err := os.MkdirAll(absConfigDir, 0750); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	configs := GenerateConfigs(opts)

	fileMap := []struct {
		name string
		data string
	}{
		{"main.cf", configs.MainCF},
		{"master.cf", configs.MasterCF},
		{"pgsql-virtual-mailbox-domains.cf", configs.VirtualMailboxDomainsCF},
		{"pgsql-virtual-mailbox-maps.cf", configs.VirtualMailboxMapsCF},
		{"pgsql-virtual-alias-maps.cf", configs.VirtualAliasMapsCF},
		{"pgsql-sender-login-maps.cf", configs.SenderLoginMapsCF},
	}

	for _, item := range fileMap {
		targetPath := filepath.Join(absConfigDir, item.name)
		if err := atomicWriteFile(absConfigDir, targetPath, []byte(item.data), 0640); err != nil {
			return fmt.Errorf("failed writing %s: %w", item.name, err)
		}
	}

	return nil
}

func atomicWriteFile(dir, targetPath string, content []byte, perm os.FileMode) error {
	tempFile, err := os.CreateTemp(dir, "postfix-conf-*")
	if err != nil {
		return err
	}
	tempPath := tempFile.Name()
	defer func() {
		if _, err := os.Stat(tempPath); err == nil {
			_ = os.Remove(tempPath)
		}
	}()

	if _, err := tempFile.Write(content); err != nil {
		_ = tempFile.Close()
		return err
	}

	if err := tempFile.Sync(); err != nil {
		_ = tempFile.Close()
		return err
	}

	if err := tempFile.Close(); err != nil {
		return err
	}

	if err := os.Chmod(tempPath, perm); err != nil {
		return err
	}

	return os.Rename(tempPath, targetPath)
}

func MaskSecret(s string) string {
	if len(s) <= 4 {
		return "****"
	}
	return s[:2] + strings.Repeat("*", len(s)-4) + s[len(s)-2:]
}
